---
- hosts: client
  tasks:
  - name: Installing software-properties-common 
    apt: name=software-properties-common state=present
  - name: Adding repository cloud-archive:mitaka
    shell: add-apt-repository cloud-archive:mitaka
  - name: apt-get update
    apt: update_cache=yes 
  - name: apt-get upgrade
    apt: upgrade=full 
  - name: Installing python openstackclient
    apt: name=python-openstackclient state=present
