---
     - mysql_db: name=neutron state=present
     - shell: mysql -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY 'pramati123';"
     - shell: mysql -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%'  IDENTIFIED BY 'pramati123';"
     - copy: src=/etc/ansible/playbooks/roles/templates/neutron.prerequisites.sh dest=/root
     - name: create roles user endpoints
       shell: bash /root/neutron.prerequisites.sh
     - name: Install self service network on controller node
       apt: name={{ item }}  state=present force=yes
       with_items:
       - neutron-server
       - neutron-linuxbridge-agent
       - neutron-plugin-ml2
       - neutron-l3-agent
       - neutron-dhcp-agent
       - neutron-metadata-agent
     - name: Updating  default section of SelfService Network neutron.conf
       ini_file: dest=/etc/neutron/neutron.conf
                 section=DEFAULT
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'core_plugin' , value: 'ml2' }
       - { name: 'service_plugins' , value: 'router' }
       - { name: 'allow_overlapping_ips' , value: 'True' }
       - { name: 'rpc_backend' , value: 'rabbit' }
       - { name: 'auth_strategy' , value: 'keystone' }
       - { name: 'notify_nova_on_port_status_changes' , value: 'True' }
       - { name: 'notify_nova_on_port_data_changes' , value: 'True' }
     - name: Updating database connection address in SelfService Network neutron.conf
       ini_file: dest=/etc/neutron/neutron.conf
                 section=database
                 option=connection 
                 value=mysql+pymysql://neutron:pramati123@controller/neutron
     - name: Updating oslo_messaging_rabbit section in SelfService Network neutron.conf
       ini_file: dest=/etc/neutron/neutron.conf
                 section=oslo_messaging_rabbit
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'rabbit_host' , value: 'controller' }
       - { name: 'rabbit_userid' , value: 'openstack' }
       - { name: 'rabbit_password', value: 'pramati123' }
     - name: Updating keystone_authtoken section in SelfService Network neutron.conf
       ini_file: dest=/etc/neutron/neutron.conf
                 section=keystone_authtoken
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'auth_uri' , value: 'http://controller:5000' }
       - { name: 'auth_url' , value: 'http://controller:35357' }
       - { name: 'memcached_servers' , value: 'controller:11211' }
       - { name: 'auth_type' , value: 'password' }
       - { name: 'project_domain_name' , value: 'default' }
       - { name: 'user_domain_name' , value: 'default' }
       - { name: 'project_name' , value: 'service' }
       - { name: 'username' , value: 'neutron' }
       - { name: 'password' , value: 'pramati123' }
     - name: Updating nova section in SelfService Network neutron.conf 
       ini_file: dest=/etc/neutron/neutron.conf
                 section=nova
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'auth_url' , value: 'http://controller:35357' }
       - { name: 'auth_type' , value: 'password' }
       - { name: 'project_domain_name' , value: 'default' }
       - { name: 'user_domain_name' , value: 'default' }
       - { name: 'project_name' , value: 'service' }
       - { name: 'region_name' , value: 'RegionOne' }
       - { name: 'username' , value: 'neutron' }
       - { name: 'password' , value: 'pramati123' }
     - name: Configuring ml2 section in SelfService Network ml2_conf.ini
       ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                 section=ml2
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'type_drivers' , value: 'flat,vlan,vxlan' }
       - { name: 'tenant_network_types' , value: 'vxlan' }
       - { name: 'mechanism_drivers' , value: 'linuxbridge,l2population' }
       - { name: 'extension_drivers' , value: 'port_security' }
     - name: Configuring ml2_type_flat section in SelfService Network ml2_conf.ini
       ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                 section=ml2_type_flat
                 option=flat_networks
                 value=provider
     - name: Configuring ml2_type_vxlan section in SelfService Network ml2_conf.ini
       ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                 section=ml2_type_vxlan
                 option=vni_ranges
                 value=1:1000
     - name: Configuring securitygroup section in SelfService Network ml2_conf.ini
       ini_file: dest=/etc/neutron/plugins/ml2/ml2_conf.ini
                 section=securitygroup
                 option=enable_ipset
                 value=True
     - name: Configuring linuxbridge section in SelfService Network linuxbridge_agent.ini
       ini_file: dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
                 section=linux_bridge
                 option=physical_interface_mappings
                 value=public:eth1
     - name: Configure vxlan section in SelfService Network linuxbridge_agent.ini
       ini_file: dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
                 section=vxlan
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'enable_vxlan' , value: 'True' }
       - { name: 'local_ip' , value: '172.16.20.96' }
       - { name: 'l2_population' , value: 'True' }
     - name: Configure security group section in SelfService Network linuxbridge_agent.ini
       ini_file: dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
                 section=securitygroup
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'enable_security_group' , value: 'True' }
       - { name: 'firewall_driver' , value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver' }
     - name: Configuring default section in SelfService Network l3_agent.ini
       ini_file: dest=/etc/neutron/l3_agent.ini
                 section=DEFAULT
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'interface_driver' , value: 'neutron.agent.linux.interface.BridgeInterfaceDriver' }
       - { name: 'external_network_bridge' , value: ' '}
     - name: Configuring default section in dhcp_agent.ini
       ini_file: dest=/etc/neutron/dhcp_agent.ini 
                 section=DEFAULT
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'interface_driver' , value: 'neutron.agent.linux.interface.BridgeInterfaceDriver' }
       - { name: 'dhcp_driver' , value: 'neutron.agent.linux.dhcp.Dnsmasq' }
       - { name: 'enable_isolated_metadata' , value: 'True' }
       - { name: 'dnsmasq_config_file' , value: '/etc/neutron/dnsmasq-neutron.conf' }
     - name: Configure default section in meta data agent
       ini_file: dest=/etc/neutron/metadata_agent.ini
                 section=DEFAULT
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'nova_metadata_ip' , value: 'controller' }
       - { name: 'metadata_proxy_shared_secret' , value: 'pramati123' }

     - name: Configure default section in nova.conf
       ini_file: dest=/etc/nova/nova.conf
                 section=neutron
                 option={{ item.name }}
                 value={{ item.value }}
       with_items:
       - { name: 'url' , value: 'http://controller:9696' }
       - { name: 'auth_url' , value: 'http://controller:35357' }
       - { name: 'auth_type' , value: 'password' }
       - { name: 'project_domain_name' , value: 'default' }
       - { name: 'user_domain_name' , value: 'default' }
       - { name: 'region_name' , value: 'RegionOne' }
       - { name: 'project_name ' , value: 'service' }
       - { name: 'username' , value: 'neutron' }
       - { name: 'password ' , value: 'pramati123' }
       - { name: 'service_metadata_proxy' , value: 'True' }
       - { name: 'metadata_proxy_shared_secret ' , value: 'pramati123' }
     - name: Populating the data base by running db sysnc command
       shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
     - name: service nova-api restart
       service: name=nova-api state=restarted
     - name: service neutron server restart
       service: name=neutron-server state=restarted
     - name: service neutron-dhcp-agent restart
       service: name=neutron-dhcp-agent state=restarted
     - name: service neutron-metadata-agent restart
       service: name=neutron-metadata-agent state=restarted
     - name: service neutron-l3-agent restart
       service: name=neutron-l3-agent state=restarted
     - name: service neutron-linuxbridge-agent restart
       service: name=neutron-linuxbridge-agent state=restarted
