---
    - name: Install nova-compute in  compute node
      apt: name={{ item }}  state=present force=yes
      with_items:
      - nova-compute
    - name: Update database connection address in nova.conf
      ini_file: dest=/etc/nova/nova.conf
                section=DEFAULT
                option={{ item.name }}
                value={{ item.value }}
      with_items:
      - { name: 'my_ip' , value: '172.16.20.116' }
      - { name: 'rpc_backend' , value: 'rabbit' }
      - { name: 'auth_strategy' , value: 'keystone' }
      - { name: 'use_neutron' , value: 'True' }
      - { name: 'firewall_driver' , value: 'nova.virt.firewall.NoopFirewallDriver' }
    - name: Update oslo_messaging_rabbit in nova.conf
      ini_file: dest=/etc/nova/nova.conf
                section=oslo_messaging_rabbit
                option={{ item.name }}
                value={{ item.value }}
      with_items:
       - { name: 'rabbit_host' , value: 'controller' }
       - { name: 'rabbit_userid' , value: 'openstack' }
       - { name: 'rabbit_password', value: 'pramati123' }
    - name: Update keystone_authtoken innova.conf
      ini_file: dest=/etc/nova/nova.conf
                 section=keystone_authtoken
                 option={{ item.name }}
                 value={{ item.value }}
      with_items:
       - { name: 'auth_uri' , value: 'http://controller:5000' }
       - { name: 'auth_url' , value: 'http://controller:35357' }
       - { name: 'auth_type' , value: 'password' }
       - { name: 'project_domain_name' , value: 'default' }
       - { name: 'user_domain_name' , value: 'default' }
       - { name: 'memcached_server' , value: 'controller:11211' }
       - { name: 'project_name' , value: 'service' }
       - { name: 'username' , value: 'nova' }
       - { name: 'password' , value: 'pramati123' }
    - name: Update vnc values in nova.conf
      ini_file: dest=/etc/nova/nova.conf
                 section=vnc
                 option={{ item.name }}
                 value={{ item.value }}
      with_items:
       - { name: 'enabled' , value: 'True' }
       - { name: 'vncserver_listen' , value: '0.0.0.0' }
       - { name: 'vncserver_proxyclient_address' , value: '$my_ip' }
       - { name: 'novncproxy_base_url' , value: 'http://controller:6080/vnc_auto.html' }
    - name: Update glance  in glance.conf
      ini_file: dest=/etc/nova/nova.conf
                 section=glance
                 option=api_servers
                 value=http://controller:9292
    - name: Update oslo_concurrency in glance.conf
      ini_file: dest=/etc/nova/nova.conf
                 section=oslo_concurrency
                 option=lock_path
                 value=/var/lib/nova/tmp
    - name: Updating libvirt section in nova-compute.conf
      ini_file: dest=/etc/nova/nova-compute.conf
                section=libvirt
                option=virt_type
                value=qemu
    - name: service nova-compute restart in compute node
      service: name=nova-compute state=restarted
    - name: removing sqlite database file
      shell: rm -f /var/lib/nova/nova.sqlite
